- name: backup librenms
  hosts: librenms_host
  vars:
    MYSQL_PASSWORD: null
    BACKUP_FOLDER: null
    db_container: "librenms_db"
    sqldump: "/tmp/librenms.sql"
    sqldump_compressed: "{{ sqldump }}.zip"
    rrd_zip: "/tmp/rrd.zip"
  tasks:
    - name: Assert MYSQL_PASSWORD is set
      assert:
        that:
          - MYSQL_PASSWORD is defined
        fail_msg: "MYSQL_PASSWORD is not set. Please provide a value."

    - name: Assert BACKUP_FOLDER is set
      assert:
        that:
          - BACKUP_FOLDER is defined
        fail_msg: "BACKUP_FOLDER is not set. Please provide a value."

    - name: Install requests module using pip3
      pip:
        name: requests
        executable: pip3
    
    - name: Dump the librenms database to a file inside the librenms db docker container
      community.docker.docker_container_exec:
        container: "{{ db_container }}"
        command: "sh -c 'mysqldump librenms -u librenms --password={{ MYSQL_PASSWORD }} > {{ sqldump }}'"

    - name: Copy librenms database dump from the db docker containr to the librenms server
      shell: docker cp {{ db_container }}:{{ sqldump }} {{ sqldump }}

    - name: Remove the librenms database dump from the db docker container
      community.docker.docker_container_exec:
        container: "{{ db_container }}"
        command: "rm {{ sqldump }}"

    - name: Compress the mysqldump file on the librenms server
      shell: zip {{ sqldump_compressed }} {{ sqldump }}

    - name: Remove the uncompressed mysqldump file from the librenms server
      shell: rm {{ sqldump }}

    - name: Copy the librenms database dump to here
      fetch:
        src: "{{ sqldump_compressed }}"
        dest: "{{ BACKUP_FOLDER }}/"
        flat: yes

    - name: Remove the compressed mysqldump file from the librenms server
      file:
        path: "{{ sqldump_compressed }}"
        state: absent


    - name: Zip the RRD directory on the librenms server
      shell: "cd /root/librenms_deployment3/compose/librenms/ && zip -q -r {{ rrd_zip }} rrd"

    - name: Fetch the RRD zip from the librenms server to here
      fetch:
        src: "{{ rrd_zip }}"
        dest: "{{ BACKUP_FOLDER }}/"
        flat: yes

    - name: Remove the compressed mysqldump file on the librenms server
      file:
        path: "{{ rrd_zip }}"
        state: absent
